development:
  adapter: postgresql
  encoding: unicode
  database: trader_helper_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: trader_helper_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: trader_helper_production
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 123456
